#!/usr/bin/env bash
# Script redirection
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World" > ~/index.html
sudo cp ~/index.html /var/www/html/index.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://twitter.com/JuanS_Tovar permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
