#!/usr/bin/env bash
# Script redirection
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://twitter.com/JuanS_Tovar permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
