#!/usr/bin/env bash
#  404 error
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo sed -i "/redirect_me/ a\\\terror_page 404 /404.html;" /etc/nginx/sites-available/default
sudo service nginx restart
