#!/usr/bin/env bash
# Script to install HAProxy for Load_Balancer

CONFIG="
frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back
backend http_back
    balance roundrobin
    server web-01 35.185.4.79:80 check
    server web-02 35.196.72.165:80 check 
"
sudo add-apt-repository -y ppa:vbernat/haproxy-1.7
apt-get -y update && apt-get -y install haproxy
echo "$CONFIG" >> /etc/haproxy/haproxy.cfg
service haproxy restart
