#!/usr/bin/env bash
# Write a Bash script that pings an IP address passed as an argument.
var=$#
case $var in
    1)
	ping -c 5 "$@"
	;;
    *)
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
	;;
esac
