#!/usr/bin/env bash
#  Bash script that:Creates the file /var/run/holbertonscript.pid containing its PID
echo $$ > holbertonscript.pid
sudo mv holbertonscript.pid /var/run/

for ((;;))
    do
	trap 'sudo rm /var/run/holbertonscript.pid && echo I hate the kill command && exit' SIGTERM SIGQUIT
	trap 'echo Y U no love me?!' SIGINT
	echo To infinity and beyond
	sleep 2
    done
