#!/usr/bin/env bash
# create nginx user and modify permissions and ports
sudo service nginx stop
sed -i -E 's/#user.+\;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/ -R
chmod 644 /etc/nginx/nginx.conf
for pid in $(pidof apache2); do
    kill "$pid"
done
su -c 'service nginx start' nginx
